import type { FactSheet, Property } from './types'

const FS_MORTGAGE_OFF: NonNullable<FactSheet['mortgage']> = {
  hasMortgage: false,
  lender: '',
  loanNumber: '',
  originalAmount: null,
  outstandingBalance: null,
  monthlyPayment: null,
  interestRate: null,
  rateType: '',
  termMonths: null,
  startDate: '',
  endDate: '',
}

/** Four sample properties for new accounts. Only the first is mortgaged; the other three are owned outright. */
export function createSeedProperties(): Property[] {
  const now = Date.now()

  return [
    // 1 — Downtown apartment, rented
    {
      id: now,
      owner: 'James Rivera',
      name: 'Downtown Loft',
      address: '350 5th Avenue, Apt 12B',
      neighbourhood: 'Midtown',
      postalCode: '',
      city: 'New York',
      country: 'United States',
      currency: 'USD',
      latitude: 40.7484,
      longitude: -73.9856,
      area: 75,
      bedrooms: 2,
      bathrooms: 1,
      parking: 0,
      storageUnits: 1,
      concierge: true,
      terrace: 0,
      balcony: 0,
      floors: 0,
      year: 2026,
      contracts: [
        {
          id: now + 1,
          status: 'active',
          tenant: 'Sarah Johnson',
          contractManager: '',
          monthlyRent: 3200,
          startDate: '2025-06-01',
          endDate: '2026-05-31',
          paymentDay: 1,
          deposit: 2,
          increment: 'fixed',
          ipcExtra: 0,
          adminFee: 250,
          notes: '',
        },
      ],
      months: {
        2026: {
          0: { status: 'rented', incomeOverride: null, expenses: { admin: 250, electricity: 95, water: 60, insurance: 180 } },
          1: { status: 'rented', incomeOverride: null, expenses: { admin: 250, electricity: 110, water: 60, insurance: 180 } },
          2: { status: 'rented', incomeOverride: null, expenses: { admin: 250, electricity: 88, water: 60, insurance: 180 } },
        },
      },
      capex: [
        {
          id: now + 2,
          date: '2025-08-15',
          dateEnd: '2025-09-20',
          desc: 'Kitchen renovation',
          cat: 'Improvement',
          amount: 12500,
        },
      ],
      taxes: { items: [{ id: now + 3, taxId: 'NYC-2026', amount: 4800, dueDate: '2026-07-01', status: 'pending' }] },
      services: {
        2026: [
          { id: now + 4, provider: 'ConEd', type: 'Electricity', accountNumber: '4412-9983', monthlyCost: 95, notes: '' },
          { id: now + 5, provider: 'NYC Water', type: 'Water', accountNumber: 'WB-00214', monthlyCost: 60, notes: '' },
        ],
      },
      factSheet: {
        propertyType: 'Apartment',
        estrato: null,
        yearBuilt: 2018,
        lastRenovation: 2025,
        floor: 12,
        matriculaInmobiliaria: '',
        cedulaCatastral: '',
        chip: '',
        customId: '',
        purchasePrice: 595000,
        purchaseDate: '2024-01-15',
        currentValue: null,
        valuationDate: '',
        photos: [],
        contacts: [],
        notes: '',
        appreciationRate: 3.5,
        projectionYears: 15,
        valueEquityView: 'mortgage',
        mortgage: {
          hasMortgage: true,
          lender: 'First National Bank',
          loanNumber: 'MTG-88421',
          originalAmount: 476000,
          downPayment: 119000,
          outstandingBalance: 465000,
          monthlyPayment: null,
          interestRate: 6.625,
          rateType: 'fixed',
          termMonths: 360,
          startDate: '2024-01-15',
          endDate: '2054-01-15',
        },
      },
    },

    // 2 — Suburban house, rented
    {
      id: now + 100,
      owner: 'James Rivera',
      name: 'Maple Street House',
      address: '742 Maple Street',
      neighbourhood: 'Oak Park',
      postalCode: '',
      city: 'Austin',
      country: 'United States',
      currency: 'USD',
      latitude: 30.2672,
      longitude: -97.7431,
      area: 140,
      bedrooms: 3,
      bathrooms: 2,
      parking: 2,
      storageUnits: 0,
      concierge: false,
      terrace: 20,
      balcony: 0,
      floors: 0,
      year: 2026,
      contracts: [
        {
          id: now + 101,
          status: 'active',
          tenant: 'Michael Chen',
          contractManager: '',
          monthlyRent: 2400,
          startDate: '2025-09-01',
          endDate: '2026-08-31',
          paymentDay: 1,
          deposit: 2,
          increment: 'none',
          ipcExtra: 0,
          adminFee: 0,
          notes: 'Pet allowed (1 dog)',
        },
      ],
      months: {
        2026: {
          0: { status: 'rented', incomeOverride: null, expenses: { electricity: 145, water: 80, gas: 65, insurance: 120, maintenance: 50 } },
          1: { status: 'rented', incomeOverride: null, expenses: { electricity: 160, water: 80, gas: 70, insurance: 120, maintenance: 50 } },
          2: { status: 'rented', incomeOverride: null, expenses: { electricity: 130, water: 85, gas: 55, insurance: 120, maintenance: 200 } },
        },
      },
      capex: [],
      taxes: { items: [{ id: now + 102, taxId: 'TX-2026-4821', amount: 3200, dueDate: '2026-01-31', status: 'paid' }] },
      services: {
        2026: [
          { id: now + 103, provider: 'Austin Energy', type: 'Electricity', accountNumber: 'AE-55123', monthlyCost: 145, notes: '' },
          { id: now + 104, provider: 'Austin Water', type: 'Water', accountNumber: 'AW-33012', monthlyCost: 80, notes: '' },
          { id: now + 105, provider: 'Texas Gas', type: 'Gas', accountNumber: 'TG-8812', monthlyCost: 65, notes: '' },
        ],
      },
      factSheet: {
        propertyType: 'House',
        estrato: null,
        yearBuilt: 2005,
        lastRenovation: null,
        floor: null,
        matriculaInmobiliaria: '',
        cedulaCatastral: '',
        chip: '',
        customId: '',
        purchasePrice: 410000,
        purchaseDate: '2020-08-01',
        currentValue: null,
        valuationDate: '',
        photos: [],
        contacts: [],
        notes: '',
        appreciationRate: 4.5,
        projectionYears: 15,
        valueEquityView: 'history',
        mortgage: { ...FS_MORTGAGE_OFF } as NonNullable<FactSheet['mortgage']>,
      },
    },

    // 3 — Beachfront condo, vacant
    {
      id: now + 200,
      owner: 'Laura Kim',
      name: 'Ocean View Condo',
      address: '1200 Coastal Blvd, Unit 8A',
      neighbourhood: 'South Beach',
      postalCode: '',
      city: 'Miami',
      country: 'United States',
      currency: 'USD',
      latitude: 25.7617,
      longitude: -80.1918,
      area: 95,
      bedrooms: 2,
      bathrooms: 2,
      parking: 1,
      storageUnits: 1,
      concierge: true,
      terrace: 0,
      balcony: 12,
      floors: 0,
      year: 2026,
      contracts: [],
      months: {
        2026: {
          0: { status: 'vacant', incomeOverride: null, expenses: { admin: 450, electricity: 70, water: 40, insurance: 310 } },
          1: { status: 'vacant', incomeOverride: null, expenses: { admin: 450, electricity: 65, water: 40, insurance: 310 } },
          2: { status: 'vacant', incomeOverride: null, expenses: { admin: 450, electricity: 75, water: 40, insurance: 310 } },
        },
      },
      capex: [
        { id: now + 201, date: '2026-01-20', desc: 'AC unit replacement', cat: 'Equipment', amount: 4200 },
      ],
      taxes: { items: [{ id: now + 202, taxId: 'FL-2026-0088', amount: 5600, dueDate: '2026-03-31', status: 'pending' }] },
      factSheet: {
        propertyType: 'Apartment',
        estrato: null,
        yearBuilt: 2020,
        lastRenovation: null,
        floor: 8,
        matriculaInmobiliaria: '',
        cedulaCatastral: '',
        chip: '',
        customId: '',
        purchasePrice: 548000,
        purchaseDate: '2018-03-01',
        currentValue: null,
        valuationDate: '',
        photos: [],
        contacts: [],
        notes: 'Looking for tenant — target rent $3,800/mo',
        appreciationRate: 5,
        projectionYears: 15,
        valueEquityView: 'history',
        mortgage: { ...FS_MORTGAGE_OFF } as NonNullable<FactSheet['mortgage']>,
      },
    },

    // 4 — Studio apartment, rented (London, GBP)
    {
      id: now + 300,
      owner: 'Daniel Osei',
      name: 'Kensington Studio',
      address: '18 Cromwell Road, Flat 3',
      neighbourhood: 'South Kensington',
      postalCode: '',
      city: 'London',
      country: 'United Kingdom',
      currency: 'GBP',
      latitude: 51.4958,
      longitude: -0.1745,
      area: 42,
      bedrooms: 1,
      bathrooms: 1,
      parking: 0,
      storageUnits: 0,
      concierge: false,
      terrace: 0,
      balcony: 0,
      floors: 0,
      year: 2026,
      contracts: [
        {
          id: now + 301,
          status: 'active',
          tenant: 'Emma Williams',
          contractManager: 'Foxtons',
          monthlyRent: 1850,
          startDate: '2025-12-01',
          endDate: '2026-11-30',
          paymentDay: 1,
          deposit: 2,
          increment: 'none',
          ipcExtra: 0,
          adminFee: 150,
          notes: '',
        },
      ],
      months: {
        2026: {
          0: { status: 'rented', incomeOverride: null, expenses: { admin: 150, electricity: 75, water: 35, insurance: 95 } },
          1: { status: 'rented', incomeOverride: null, expenses: { admin: 150, electricity: 80, water: 35, insurance: 95 } },
          2: { status: 'rented', incomeOverride: null, expenses: { admin: 150, electricity: 70, water: 35, insurance: 95 } },
        },
      },
      capex: [],
      taxes: { items: [{ id: now + 302, taxId: 'HMRC-2026', amount: 2100, dueDate: '2026-01-31', status: 'paid' }] },
      services: {
        2026: [
          { id: now + 303, provider: 'British Gas', type: 'Electricity', accountNumber: 'BG-441290', monthlyCost: 75, notes: '' },
          { id: now + 304, provider: 'Thames Water', type: 'Water', accountNumber: 'TW-88234', monthlyCost: 35, notes: '' },
        ],
      },
      factSheet: {
        propertyType: 'Studio',
        estrato: null,
        yearBuilt: 1965,
        lastRenovation: 2022,
        floor: 3,
        matriculaInmobiliaria: '',
        cedulaCatastral: '',
        chip: '',
        customId: '',
        purchasePrice: 318000,
        purchaseDate: '2016-06-01',
        currentValue: null,
        valuationDate: '',
        photos: [],
        contacts: [
          { id: now + 305, name: 'Foxtons South Ken', role: 'Property Manager', phone: '+44 20 7590 0000', email: 'southken@foxtons.co.uk' },
        ],
        notes: '',
        appreciationRate: 3.25,
        projectionYears: 12,
        valueEquityView: 'history',
        mortgage: { ...FS_MORTGAGE_OFF } as NonNullable<FactSheet['mortgage']>,
      },
    },
  ]
}
